/** Shared protocol types for the standalone uninstaller UI. */

export const UNINSTALL_PROTOCOL_VERSION = 1 as const
export const UNINSTALL_EVENT = 'uninstall:event' as const
export const UNINSTALL_CONFIRMATION = 'delete-v1' as const

export type UninstallEntry = 'installed' | 'installer' | 'registry' | 'compatFlag'
export type UninstallArch = 'x64' | 'arm64' | 'unknown'
export type InstallScope = 'perUser' | 'allUsers' | 'portable' | 'unknown'
export type DataStrategy = 'keep' | 'export' | 'delete'
export type BackupFormat = 'sabackup' | 'zip'

export type UninstallPhase =
  | 'accepted'
  | 'scanning'
  | 'validating'
  | 'stopping'
  | 'backingUp'
  | 'commit'
  | 'removingShortcuts'
  | 'removingData'
  | 'removingInstall'
  | 'removingRegistry'
  | 'verifying'
  | 'completed'
  | 'cancelled'
  | 'failed'

export type UninstallTerminal = 'completed' | 'cancelled' | 'failed'

export type UninstallErrorCode =
  | 'INVALID_REQUEST'
  | 'NO_TARGET'
  | 'TARGET_CHANGED'
  | 'TARGET_NOT_CONFIRMED'
  | 'TARGET_SCOPE_INVALID'
  | 'TARGET_IDENTITY_MISMATCH'
  | 'UNSAFE_PATH'
  | 'PATH_REPARSE_POINT'
  | 'TARGET_IS_ROOT'
  | 'TARGET_IS_PARENT'
  | 'TARGET_NOT_DIRECTORY'
  | 'TARGET_NOT_INSTALL'
  | 'ARCH_MISMATCH'
  | 'PROCESS_RUNNING'
  | 'PROCESS_STOP_FAILED'
  | 'BACKUP_PATH_INVALID'
  | 'BACKUP_PATH_IN_SCOPE'
  | 'BACKUP_PATH_UNWRITABLE'
  | 'BACKUP_PASSWORD_REQUIRED'
  | 'BACKUP_FORMAT_INVALID'
  | 'BACKUP_INCOMPLETE'
  | 'BACKUP_EXPORT_FAILED'
  | 'DELETE_FAILED'
  | 'REGISTRY_FAILED'
  | 'ELEVATION_CANCELLED'
  | 'ELEVATION_FAILED'
  | 'ALREADY_RUNNING'
  | 'DUPLICATE_REQUEST'
  | 'CANCEL_TOO_LATE'
  | 'INTERNAL'

export type UninstallSource = 'HKCU' | 'HKLM'
export type IdentityConfidence = 'strong' | 'degraded'
export type UninstallEntryMode = 'standalone' | 'installer'
export type BackupCategory = 'basicData' | 'cookies' | 'indexedDB' | 'cache'

export interface UninstallTargetId {
  /** Opaque, versioned identity generated by scan. */
  token: string
}

export interface UninstallLocation {
  edition: 'concept' | 'community'
  id: UninstallTargetId
  path: string
  displayPath: string
  source: UninstallEntry[]
  scope: InstallScope
  arch: UninstallArch
  version: string | null
  registered: boolean
  registeredRoots: UninstallSource[]
  executablePresent: boolean
  resourcesPresent: boolean
  identityConfidence: IdentityConfidence
  runningPids: number[]
  removable: boolean
  nonRemovableReason?: UninstallErrorCode
  recommended: boolean
}

export interface UninstallInfo {
  protocolVersion: 1
  uninstallerVersion: string
  hostArch: UninstallArch
  entry: UninstallEntryMode
  supportsElevation: boolean
  supportsBackup: boolean
  supportsSilent: false
}

export interface UninstallScanRequest {
  // The controller binds source and caller identity; the renderer sends no path.
}

export interface DataRoot {
  path: string
  source: string
  removable: boolean
  associatedTargetIds: UninstallTargetId[]
}

export interface UninstallScanResponse {
  scanId: string
  generatedAt: string
  locations: UninstallLocation[]
  recommendedTargetId: UninstallTargetId | null
  dataRoots: DataRoot[]
}

export interface BackupSelection {
  format: BackupFormat
  outputPath: string
  encrypt: boolean
  /** Present only while the request is in memory; never log or persist it. */
  password?: string
  categories: BackupCategory[]
}

export interface UninstallRequest {
  protocolVersion: 1
  requestId: string
  scanId: string
  targetId: UninstallTargetId
  strategy: DataStrategy
  backup?: BackupSelection
  additionalTargetIds: UninstallTargetId[]
  confirmation: 'delete-v1'
}

export interface UninstallAccepted {
  requestId: string
  operationId: string
  state: 'accepted'
}

export interface BackupResult {
  path: string
  format: BackupFormat
  categories: string[]
  verified: boolean
  entryCount?: number
}

export interface UninstallError {
  code: UninstallErrorCode
  message: string
  phase: UninstallPhase
  retryable: boolean
  operationId: string
  details?: Record<string, string | number | boolean>
}

export interface UninstallResult {
  requestId: string
  operationId: string
  state: UninstallTerminal
  phase: UninstallPhase
  targetIds: UninstallTargetId[]
  removedInstallPaths: string[]
  removedDataRoots: string[]
  backup?: BackupResult
  warnings: string[]
  error?: UninstallError
}

export interface UninstallEvent {
  logPath?: string
  logError?: string
  protocolVersion: 1
  operationId: string
  requestId: string
  sequence: number
  phase: UninstallPhase
  progress: number
  message: string
  terminal: boolean
  result?: UninstallResult
}

export interface UninstallCallerIdentity {
  callerUserSid: string
  callerUserProfile: string
  launcherPath: string
  sourcePath?: string
  effectiveUserSid: string
  effectiveIsElevated: boolean
  controllerSha256: string
}

export type CancelState = 'cancelRequested' | 'tooLate' | 'notFound'

export interface CancelResponse {
  operationId: string
  accepted: boolean
  state: CancelState
}

export interface UninstallApi {
  onCloseRequested?(cb: () => void): () => void
  openLog?(logPath: string): Promise<void>
  getInfo(): Promise<UninstallInfo>
  scan(request?: UninstallScanRequest): Promise<UninstallScanResponse>
  start(request: UninstallRequest): Promise<UninstallAccepted | null>
  cancel(operationId: string): Promise<CancelResponse>
  close(): Promise<void>
  chooseBackupPath(format: BackupFormat, suggestedName: string): Promise<string>
  onEvent(cb: (event: UninstallEvent) => void): () => void
  /** Optional local adapter hooks; no additional IPC commands. */
  whenReady?(): Promise<void>
  onEventError?(cb: (error: unknown) => void): () => void
}
