// electron/presets/ai-platforms.ts — 内置 AI 平台列表
//
// AI 窗口核心功能：聚合 9 个内置 AI 平台网页版。
// 每个 AI 平台可作为特殊 Profile 类型创建（isAIPlatform=true）。

import type { AIPlatform } from '../shared/types.js'
import { IPHONE_UA, IPHONE_VIEWPORT, WIN_CHROME_UA } from './devices.js'

export const AI_PLATFORMS: AIPlatform[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    region: 'global',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea#prompt-textarea, textarea[data-id]',
    sendSelector: 'button[data-testid="send-button"], button[aria-label="发送"]',
    themeColor: '#10a37f',
    gradientColor: '#1a7f64',
    // chat.openai.com 与 chatgpt.com 同账户体系；auth.openai.com 为登录域
    allowedOrigins: [
      'https://chat.openai.com/',
      'https://chatgpt.com/',
      'https://auth.openai.com/',
      'https://auth0.openai.com/',
      'https://login.openai.com/',
    ],
    conversationUrlPatterns: ['/c/', '/g/', '/chat/', '/conversation/'],
  },
  {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    region: 'global',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'div[contenteditable=true][role=textbox]',
    sendSelector: 'button[aria-label="Send Message"], button[type="submit"]',
    themeColor: '#cc785c',
    gradientColor: '#a65539',
    // claude.ai 为主域；anthropic.com 为登录/账户域
    allowedOrigins: [
      'https://claude.ai/',
      'https://www.anthropic.com/',
      'https://auth.anthropic.com/',
      'https://console.anthropic.com/',
    ],
    conversationUrlPatterns: ['/c/', '/chat/', '/conversation/'],
  },
  {
    id: 'gemini',
    name: 'Gemini',
    url: 'https://gemini.google.com',
    region: 'global',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'rich-textarea textarea, div[contenteditable=true]',
    sendSelector: 'button[aria-label="发送"], button.send-button',
    themeColor: '#4285f4',
    gradientColor: '#1e63d6',
    // gemini.google.com 为主域；accounts.google.com 为登录；aistudio.google.com 为关联产品
    allowedOrigins: [
      'https://gemini.google.com/',
      'https://accounts.google.com/',
      'https://myaccount.google.com/',
      'https://aistudio.google.com/',
    ],
    conversationUrlPatterns: ['/app/', '/chat/', '/conversation/', '/c/'],
  },
  {
    id: 'doubao',
    name: '豆包',
    url: 'https://www.doubao.com/chat',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea[data-testid=chat_input]',
    sendSelector: 'button[data-testid="send_button"]',
    themeColor: '#3370ff',
    gradientColor: '#1a56db',
    // www.doubao.com 为主域；passport.volcengine.com / volces.com 为登录
    allowedOrigins: [
      'https://www.doubao.com/',
      'https://doubao.com/',
      'https://passport.volcengine.com/',
      'https://www.volcengine.com/',
    ],
    conversationUrlPatterns: ['/chat/', '/c/', '/conversation/'],
  },
  {
    id: 'chatglm',
    name: '智谱清言',
    url: 'https://chatglm.cn',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea, div[contenteditable=true]',
  sendSelector: 'button[class*="send"], button[class*="Send"], button[aria-label*="发送"], div[role="button"][aria-label*="发送"]',
  fileInputSelector: 'input[type=file][accept*="image" i], input[type=file]',
  themeColor: '#316cfc',
    gradientColor: '#1e4fd6',
    // chatglm.cn 为主域；bigmodel.cn 为开放平台；accounts 通用登录
    allowedOrigins: [
      'https://chatglm.cn/',
      'https://www.chatglm.cn/',
      'https://bigmodel.cn/',
      'https://open.bigmodel.cn/',
    ],
    conversationUrlPatterns: ['/chat/', '/c/', '/conversation/'],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea#chat-input',
    // 用户提供的真实发送按钮 HTML：<div role="button" class="ds-button ds-button--primary ds-button--filled ds-button--circle ds-button--m ...">
    // 必须精确匹配 class（包含 --primary --filled --circle --m），避免误中输入区域其他按钮
    sendSelector: 'div[role="button"].ds-button.ds-button--primary.ds-button--filled.ds-button--circle, div[role="button"][aria-label="发送"], button.ds-icon-button[type="button"]:last-child',
    themeColor: '#4d6bfe',
    gradientColor: '#2e4fd9',
    allowedOrigins: [
      'https://chat.deepseek.com/',
      'https://www.deepseek.com/',
      'https://platform.deepseek.com/',
    ],
    conversationUrlPatterns: ['/chat/', '/c/', '/conversation/', '/a/chat/'],
  },
  {
    id: 'kimi',
    name: 'Kimi',
    url: 'https://kimi.moonshot.cn',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea.textarea, textarea[placeholder], div[contenteditable=true]',
    sendSelector: 'button[class*="send"], button[class*="Send"], button[aria-label*="发送"], div[role="button"][aria-label*="发送"], .send-button',
    themeColor: '#12161d',
    gradientColor: '#2d3748',
    allowedOrigins: [
      'https://kimi.moonshot.cn/',
      'https://www.moonshot.cn/',
      'https://platform.moonshot.cn/',
    ],
    conversationUrlPatterns: ['/chat/', '/c/', '/conversation/'],
  },
  {
    id: 'yiyan',
    name: '文心一言',
    url: 'https://yiyan.baidu.com',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea#chat-input',
    sendSelector: 'button[class*="send"], #sendBtn',
    themeColor: '#1c7fff',
    gradientColor: '#0e5fcc',
    // yiyan.baidu.com 为主域；passport.baidu.com 为登录；chat.baidu.com 为关联产品
    allowedOrigins: [
      'https://yiyan.baidu.com/',
      'https://passport.baidu.com/',
      'https://chat.baidu.com/',
      'https://aip.baidubce.com/',
    ],
    conversationUrlPatterns: ['/chat/', '/c/', '/conversation/', '/dialog/'],
  },
  {
    id: 'mimo',
    name: '小米 Mimo',
    url: 'https://mimo.xiaomi.com',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea, div[contenteditable=true]',
    sendSelector: 'button[class*="send"], button[class*="Send"], button[aria-label*="发送"], div[role="button"][aria-label*="发送"]',
    themeColor: '#ff6b35',
    gradientColor: '#e04e1f',
    // mimo.xiaomi.com 为主域；aistudio.xiaomimimo.com / platform.xiaomimimo.com 为关联产品域，
    // 此前 window.open 跳转被拦截 loadURL 失败导致 remount 循环，纳入白名单避免开独立窗口
    allowedOrigins: [
      'https://mimo.xiaomi.com/',
      'https://aistudio.xiaomimimo.com/',
      'https://platform.xiaomimimo.com/',
      'https://account.xiaomi.com/',
      'https://auth.mi.com/',
    ],
    conversationUrlPatterns: ['/chat/', '/c/', '/conversation/', '/dialogue/'],
  },
]
