// electron/presets/ai-platforms.ts — 内置 AI 平台列表
//
// AI 窗口核心功能：聚合 9 个内置 AI 平台网页版。
// 每个 AI 平台可作为特殊 Profile 类型创建（isAIPlatform=true）。

import type { AIPlatform } from '../shared/types.js'
import { IPHONE_UA, IPHONE_VIEWPORT, WIN_CHROME_UA } from './devices.js'

export const AI_PLATFORMS: AIPlatform[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    url: 'https://chat.openai.com',
    region: 'global',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea#prompt-textarea, textarea[data-id]',
    sendSelector: 'button[data-testid="send-button"], button[aria-label="发送"]',
    themeColor: '#10a37f',
    gradientColor: '#1a7f64',
  },
  {
    id: 'claude',
    name: 'Claude',
    url: 'https://claude.ai',
    region: 'global',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'div[contenteditable=true][role=textbox]',
    sendSelector: 'button[aria-label="Send Message"], button[type="submit"]',
    themeColor: '#cc785c',
    gradientColor: '#a65539',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    url: 'https://gemini.google.com',
    region: 'global',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'rich-textarea textarea, div[contenteditable=true]',
    sendSelector: 'button[aria-label="发送"], button.send-button',
    themeColor: '#4285f4',
    gradientColor: '#1e63d6',
  },
  {
    id: 'doubao',
    name: '豆包',
    url: 'https://www.doubao.com/chat',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea[data-testid=chat_input]',
    sendSelector: 'button[data-testid="send_button"]',
    themeColor: '#3370ff',
    gradientColor: '#1a56db',
  },
  {
    id: 'chatglm',
    name: '智谱清言',
    url: 'https://chatglm.cn',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea, div[contenteditable=true]',
  sendSelector: 'button[class*="send"], button[class*="Send"], button[aria-label*="发送"], div[role="button"][aria-label*="发送"]',
  fileInputSelector: 'input[type=file][accept*="image" i], input[type=file]',
  themeColor: '#316cfc',
    gradientColor: '#1e4fd6',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    url: 'https://chat.deepseek.com',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea#chat-input',
    // 用户提供的真实发送按钮 HTML：<div role="button" class="ds-button ds-button--primary ds-button--filled ds-button--circle ds-button--m ...">
    // 必须精确匹配 class（包含 --primary --filled --circle --m），避免误中输入区域其他按钮
    sendSelector: 'div[role="button"].ds-button.ds-button--primary.ds-button--filled.ds-button--circle, div[role="button"][aria-label="发送"], button.ds-icon-button[type="button"]:last-child',
    themeColor: '#4d6bfe',
    gradientColor: '#2e4fd9',
  },
  {
    id: 'kimi',
    name: 'Kimi',
    url: 'https://kimi.moonshot.cn',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea.textarea, textarea[placeholder], div[contenteditable=true]',
    sendSelector: 'button[class*="send"], button[class*="Send"], button[aria-label*="发送"], div[role="button"][aria-label*="发送"], .send-button',
    themeColor: '#12161d',
    gradientColor: '#2d3748',
  },
  {
    id: 'yiyan',
    name: '文心一言',
    url: 'https://yiyan.baidu.com',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea#chat-input',
    sendSelector: 'button[class*="send"], #sendBtn',
    themeColor: '#1c7fff',
    gradientColor: '#0e5fcc',
  },
  {
    id: 'mimo',
    name: '小米 Mimo',
    url: 'https://mimo.xiaomi.com',
    region: 'cn',
    defaultDesktopPreset: 'win-chrome-125',
    defaultMobilePreset: 'iphone-15-pro-safari',
    defaultUA: IPHONE_UA,
    defaultResolution: IPHONE_VIEWPORT,
    defaultLanguage: 'zh-CN',
    inputSelector: 'textarea, div[contenteditable=true]',
    sendSelector: 'button[class*="send"], button[class*="Send"], button[aria-label*="发送"], div[role="button"][aria-label*="发送"]',
    themeColor: '#ff6b35',
    gradientColor: '#e04e1f',
  },
]
