import type { AppSettings } from '../shared/api/settings.api.js'

export type DefaultAppSettings = AppSettings

export function getDefaultAppSettings(isPortable: boolean): DefaultAppSettings {
  return {
    hideForeignModels: true,
    tabBarCollapsed: true,
    proxyMode: 'system',
    customProxy: '',
    proxyUsername: '',
    proxyPassword: '',
    proxyBypass: '',
    hiddenPlatforms: [],
    enterToSend: true,
    defaultDesktopUaPreset: 'win-chrome-125',
    defaultMobileUaPreset: 'iphone-15-pro-safari',
    // Installed applications keep their tray session by default.
    closeBehavior: isPortable ? 'close' : 'minimize',
    autoLaunch: false,
    silentStart: false,
    autoUpdate: true,
    logLevel: 'info',
    uiScale: 'medium',
    startupOpen: 'lastConversation',
    onboardingCompleted: false,
    topBarVisibleButtons: ['navBack', 'navForward', 'navHome', 'pinToggle'],
    appClickBehavior: 'switch',
    cacheAutoClean: 'never',
    lastCacheCleanAt: 0,
    downloadDir: '',
    downloadBehavior: 'ask',
    altSpaceResetThreshold: 6,
    proxyFallbackEnabled: false,
    proxyFallbackMode: 'direct',
    usageTrackingEnabled: true,
    cookieWhitelist: ['google.com', 'openai.com'],
    cookieBlacklist: [],
    cookiePopupCooldownMs: 60000,
    cookieHandlerEnabled: true,
    defaultAdvancedPanelTab: 'chat',
    whiteboardSidebarVisible: false,
    disableAllBlockRules: false,
    notesSidebarWidth: 160,
    notesSidebarCollapsed: false,
    notesRestoreCursor: true,
    chatSidebarWidth: 130,
    chatSidebarCollapsed: false,
    chatInputCursorPos: 0,
    advancedPanelTabSwitchShortcuts: true,
    whiteboardSidebarWidth: 130,
    whiteboardSidebarCollapsed: false,
    popupWhitelist: [],
    browserTabPersistence: 'memory',
    defaultSearchEngine: { name: 'Bing', urlTemplate: 'https://www.bing.com/search?q={query}' },
  }
}
